# Generated by Django 6.0.6 on 2026-06-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requirements',
            field=models.TextField(blank=True, help_text='Describe your project, ideas, and what you need.'),
        ),
    ]
