# Generated by Django 6.0.6 on 2026-06-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_order_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='submission_file',
            field=models.FileField(blank=True, help_text='Upload completed file', null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='order',
            name='submission_text',
            field=models.TextField(blank=True, help_text='Submission message or links (e.g. Google Drive, GitHub)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('progress', 'In Progress'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
